name: Publish charm

on:
  push:
    branches:
      - track/**
    paths-ignore:
      - '.github/workflows/ci.yaml'

jobs:
  tests:
    name: Release tests
    uses: ./.github/workflows/tests.yaml

  collect-build-platforms:
    name: Collect charm build platforms
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Gather platforms
        id: gather_platforms
        run: |
          platforms=$(yq -o json -I 0 '.platforms | keys' charmcraft.yaml | sed "s/amd64/ubuntu-latest/g" | sed "s/arm64/ubuntu-24.04-arm/g")

          echo "platforms=$platforms" >> "$GITHUB_OUTPUT"
    outputs:
      platforms: ${{ steps.gather_platforms.outputs.platforms }}

  build:
    strategy:
      matrix:
        platform: ${{ fromJSON(needs.collect-build-platforms.outputs.platforms) }}
    name: 'Build charm | ${{ matrix.platform }}'
    needs:
      - collect-build-platforms
    runs-on: ${{ matrix.platform }}
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Upload charm package
        uses: canonical/charming-actions/upload-charm@2.6.2
        with:
          credentials: ${{ secrets.CHARMCRAFT_CREDENTIALS }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          channel: 3.1/edge
          tag-prefix: airflow-coordinator
          charmcraft-channel: 3.x/stable
