name: Tests

on:
  pull_request

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install dependencies
        run: |
          sudo snap install astral-uv --classic
          uv tool install tox

          sudo snap install just

      - name: Run lint
        run: just lint

  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install dependencies
        run: |
          sudo snap install astral-uv --classic
          uv tool install tox

          sudo snap install just

      - name: Run unit tests
        run: just unit

  integration-tests:
    name: Integration tests
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install dependencies
        run: |
          sudo snap install astral-uv --classic
          uv tool install tox

          sudo snap install just

      - name: Run unit tests
        run: just integration
